### ISSUE TITLE
Incorrect result in The Cyclone when line 13 is true 

### ISSUE THREAD

**Issue by caesiumtea** [codedex-io/python-101#29]
Kids ride for free whoooo!

When `height >= 100 and with_taller_person` is True, this code doesn't check whether `credits >= 10`.
https://github.com/codedex-io/python-101/blob/02f99003f6d0a306a0a9ebab593227800cb9cfdf/3-control-flow/15_the_cyclone_2.py#L13-L14

![](https://cdn.discordapp.com/attachments/1025763055646285884/1083882395503169606/image.png)
Code editor showing output "Enjoy the ride!" while `credits = 0`.

It looks like an easy fix is to move up lines 15-16 and place them at line 10 instead, so that credits are checked first before height. But maybe you don't want that, since it changes what the output is when the person is both too short and also doesn't have credits.

**Comment by Dusch4593** [comment]
hey @caesiumtea thanks so much for flagging this! I just opened and connect [PR #31](https://github.com/codedex-io/python-101/pull/31/files) to this issue. Could you try out the new code and let me know if you find any more bugs? 🐛

**Comment by caesiumtea** [comment]
I tried out the one in commit 6f33c406dc82edae47214c3d3eb65352fdd5a491 and it seems like it's working! Though, the current code in commit 5245991 is back to giving the wrong answer.
