### ISSUE TITLE
Temperature Converter

### ISSUE THREAD

**Issue by sanjeewa311** [codedex-io/python-101#36]
Tempreature_Fahrenheit = float(input("what is the temperature in F: " ))
Celsius =round((Tempreature_Fahrenheit - 32) / 1.8 , 2)
print('Tempreature in Celsius: ', Celsius)

**Comment by Dusch4593** [comment]
Hi @sanjeewa311! This is Brandon from Codédex. Just wanted to follow up on this!

Was this a suggestion for an alternative solution to the "Temperature" exercise in our Python course?

I love this solution, but I'm not sure it would fit with this exercise at this point in the course for the following reasons:

- The `input()` function is actually introduced for the first time in the course two exercises later (in 9. Pythagorean Theorem).
- The `float()` and `round()` functions are not actually used in the course! While these are both solid built-in Python functions, we didn't want to include too many of them in this course that is oriented towards beginners of Python (or code, in general).

Hope this helps and thank you for the suggestion! 😄 

cc: @sonnynomnom

**Comment by sonnynomnom** [comment]
Great answer @Dusch4593! +1 and closing this one for now. 🙏
