### ISSUE TITLE
[SOLVED] Bonus article link from The Legend of Python without option to open on a new tab

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/python-101#39]
Hello team,

This issue was already reported and solved previously with other links. Now is another one from this [endpoint](https://www.codedex.io/python) that does not have the option to be opened in a new tab. See new_tab_issue01.png. 👇

![new_tab_issue01](https://github.com/codedex-io/python-101/assets/48260426/2f4ca878-54d3-488b-9020-f843310318cc)

There is another link with the same issue in this [endpoint](https://www.codedex.io/home), see new_tab_issue02.png. 👇
![new_tab_issue02](https://github.com/codedex-io/python-101/assets/48260426/d1d09d99-f520-4565-ac65-c1293af8501f)

**Comment by MilanGrujicic** [comment]
Still on The Legend of Python page, the link to challenge packs under bonus article also does not open in a new tab.

**Comment by asiqurrahman** [comment]
He Milan, this has been fixed and you've gained +2 points for it.
There are most likely more bugs like this on the site, which I am auditing and already fixing. So any bug report similar to this moving forward will not be counted towards the points system. But definitely feel free to report it, if you do run into one.
