### ISSUE TITLE
typo in quadratic part of variables in python 101

### ISSUE THREAD

**Issue by pranshavpatel** [codedex-io/python-101#5]
Hey, there is a typo in the first sentence of the website
[https://www.codedex.io/python/09-quadratic](url)
``` Thus far, we've only been outputting things to the user, which makes our programs very one-sided and not that fun. ```
Here instead of `Thus`, `This` should have been written.

**Comment by sonnynomnom** [comment]
Hi @pranshavpatel, I think we are going to stick with "thus far" if that's alright!

**Comment by sonnynomnom** [comment]
Keep the feedback coming though!

**Comment by pranshavpatel** [comment]
Alright, I guess I misinterpreted
