### ISSUE TITLE
Typos from The Legend of Python

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/python-101#55]
Hello team,

Please find below a list of typos from The Legend of Python lessons.

### 06. Data Types
- Replace 'they' with 'it', see typo01.png. 👇
![typo01](https://github.com/codedex-io/python-101/assets/48260426/40017fc3-b1c9-4c19-955e-6ff39b21cf5c)

### 09. Pythagorean Theorem
- Replace 'press' with 'presses', see typo02.png.  👇
![typo02](https://github.com/codedex-io/python-101/assets/48260426/f3e6d412-dbf6-4a39-8e5f-2e9d57bb6521)

### 10. Currency
- Replace 'peso' with 'pesos', see typo03.png. 👇
![typo03](https://github.com/codedex-io/python-101/assets/48260426/35706480-6d01-4c96-a41e-af3902c99f76)

### 12. Grades
- Replace 'claus' with 'clauses', see typo04.png.  👇
![typo04](https://github.com/codedex-io/python-101/assets/48260426/fd805919-ecaa-4a23-b352-d3c3fc668b8c)

### 16. Sorting Hat
- Add 'have' after 'we'
- Replace 'learnings' with 'learning', see typo05.png. 👇
![typo05](https://github.com/codedex-io/python-101/assets/48260426/51dea1d0-5f6b-48b7-9b81-984883b3b2d1)

### 21. Fizzbuzz
- Replace 'learnings' with 'learning', see typo06.png. 👇
![typo06](https://github.com/codedex-io/python-101/assets/48260426/3b8c5aca-c6cc-4b01-8aac-e17688861e23)

**Comment by sonnynomnom** [comment]
Omg these are great!

**Comment by sonnynomnom** [comment]
Hi Milan! OMG these are great!

I fixed everything except "learnings" and also "we learned", because they are fine according to Grammarly! 

Great job tho!!!
