### ISSUE TITLE
wrong output documented

### ISSUE THREAD

**Issue by pranshavpatel** [codedex-io/python-101#6]
In the Magic 8 Ball part of python 101:
[](url)
The documentation goes as follows:

Together, the code will look like:
```py
import random
num = random.randint(1, 9)
print(num)
```
`The output should be different each time it runs: 2, 0, 8, 5, 9, 2, 1, 3.`

- In the last line, the output can not contain 0 as the program will only generate integers between 1 and 9

**Comment by sonnynomnom** [comment]
Great catch!!! Fixed!!!
