### ISSUE TITLE
Multiple houses

### ISSUE THREAD

**Issue by Kodoka** [codedex-io/python-101#7]
As designed, choosing options such as: 1, 3, 4 on each question respectively, would result in both Gryffindor and Ravenclaw having the same weight in determining one's house. Maybe swap the last bit, that evaluates the winning house, to something like...

```
if(ravenclaw > gryffindor and ravenclaw > slytherin and ravenclaw > hufflepuff):
    print("Ravenclaw!")
elif(gryffindor > ravenclaw and gryffindor > slytherin and gryffindor > hufflepuff):
    print("Gryffindor!")
elif(slytherin > ravenclaw and slytherin > gryffindor and slytherin > hufflepuff):
    print("Slytherin!")
elif(hufflepuff > ravenclaw and hufflepuff > gryffindor and hufflepuff > slytherin):
    print("Hufflepuff!")
else:
    print("Multiple houses.")
```

Granted your code will still spit out one winner, but I feel like it could be confusing to some as to why Gryffindor is taking priority over Ravenclaw, when they have the same amount of points. Especially since Ravenclaw should win. 😏

**Comment by ACRU-BEAST** [comment]
This is overkill but precise.

if Gryffindor > Hufflepuff:
    if Gryffindor > Slytherin:
        if Gryffindor == Ravenclaw:
            print("It's a tie! choose between: 🦁 Gryffindor & 🦅 Ravenclaw")
        elif Gryffindor > Ravenclaw:
            print("Your house is: 🦁 Gryffindor!")
        else:
            print("Your house is: 🦅 Ravenclaw!")
    elif Slytherin > Ravenclaw:
        print("Your house is: 🐍 Slytherin!")
    else:
        print("Your house is: 🦅 Ravenclaw!")
elif Hufflepuff > Ravenclaw:
    if Hufflepuff == Slytherin:
        print("It's a tie! choose between: 🦡 Hufflepuff & 🐍 Slytherin")
    elif Hufflepuff > Slytherin:
        print("Your house is: 🦡 Hufflepuff!")
    else:
        print("Your house is: 🐍 Slytherin!")
elif Ravenclaw > Slytherin:
    print ("Your house is: 🦅 Ravenclaw!")
else: 
    print("Your house is: 🐍 Slytherin!")

**Comment by ACRU-BEAST** [comment]
This is overkill but precise:

`if Gryffindor == Hufflepuff == Slytherin == Ravenclaw:
    print("It's a tie! choose between: 🦁 Gryffindor, 🦅 Ravenclaw, 🐍 Slytherin & 🦡 Hufflepuff") 
elif Gryffindor > Hufflepuff:
    if Gryffindor > Slytherin:
        if Gryffindor == Ravenclaw:
            print("It's a tie! choose between: 🦁 Gryffindor & 🦅 Ravenclaw")
        elif Gryffindor > Ravenclaw:
            print("Your house is: 🦁 Gryffindor!")
        else:
            print("Your house is: 🦅 Ravenclaw!")
    elif Slytherin > Ravenclaw:
        print("Your house is: 🐍 Slytherin!")
    else:
        print("Your house is: 🦅 Ravenclaw!")
elif Hufflepuff > Ravenclaw:
    if Hufflepuff == Slytherin:
        print("It's a tie! choose between: 🦡 Hufflepuff & 🐍 Slytherin")
    elif Hufflepuff > Slytherin:
        print("Your house is: 🦡 Hufflepuff!")
    else:
        print("Your house is: 🐍 Slytherin!")
elif Ravenclaw > Slytherin:
    print ("Your house is: 🦅 Ravenclaw!")
else: 
    print("Your house is: 🐍 Slytherin!")`

**Comment by ACRU-BEAST** [comment]
This is overkill but precise.

```
if Gryffindor == Hufflepuff == Slytherin == Ravenclaw:
    print("It's a tie! choose between: 🦁 Gryffindor, 🦅 Ravenclaw, 🐍 Slytherin & 🦡 Hufflepuff") 
elif Gryffindor > Hufflepuff:
    if Gryffindor > Slytherin:
        if Gryffindor == Ravenclaw:
            print("It's a tie! choose between: 🦁 Gryffindor & 🦅 Ravenclaw")
        elif Gryffindor > Ravenclaw:
            print("Your house is: 🦁 Gryffindor!")
        else:
            print("Your house is: 🦅 Ravenclaw!")
    elif Slytherin > Ravenclaw:
        print("Your house is: 🐍 Slytherin!")
    else:
        print("Your house is: 🦅 Ravenclaw!")
elif Hufflepuff > Ravenclaw:
    if Hufflepuff == Slytherin:
        print("It's a tie! choose between: 🦡 Hufflepuff & 🐍 Slytherin")
    elif Hufflepuff > Slytherin:
        print("Your house is: 🦡 Hufflepuff!")
    else:
        print("Your house is: 🐍 Slytherin!")
elif Ravenclaw > Slytherin:
    print ("Your house is: 🦅 Ravenclaw!")
else: 
    print("Your house is: 🐍 Slytherin!")
```
