### ISSUE TITLE
Help desk button in /pricing endpoint broken

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/python-101#71]
Hello team,

I would like to report an issue in this [page](https://www.codedex.io/pricing).

The issue is with this "Help Center" button, see attached picture for context:
![helpcenterBug](https://github.com/codedex-io/python-101/assets/48260426/52a3de93-3e5b-4019-a71f-2a62aaa8675b)

When the user clicks on that button, the user is taken to a page displaying the error:
![notionbug](https://github.com/codedex-io/python-101/assets/48260426/5e83c256-548b-4d6e-9430-92a06aef935b)

The button has the following link associated to it:
[https](https://special-pea-6f1.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[:](https://special-pea-6f1.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[//special-pea-6f1.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7](https://special-pea-6f1.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)

In the footer of the /home directory, there is also a "Help Center" button, which takes the user to the following link, which works:

[https](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[:](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[//](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[codedex.notion.site](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[/](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[Welcome](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[-](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[to](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[-](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[the](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[-](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[Cod](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[-](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[dex](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[-](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[Help](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[-](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[Center](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[-](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)[c8afe2966ea9490d9377bce826d22eb7](https://codedex.notion.site/Welcome-to-the-Cod-dex-Help-Center-c8afe2966ea9490d9377bce826d22eb7)

I would love to make a PR fixing that, but apparently mortals like myself do not have access to the repository responsible for the /pricing endpoint. 

I made an issue in the codedex.io/python-101 repo for not having anywhere else to add it.

**Comment by MilanGrujicic** [comment]
Reopened, as this bug is regarding a different component as discussed with Eric.

**Comment by sonnynomnom** [comment]
yep we are giving you a +2 for this after more discussion!
