### ISSUE TITLE
Typo in python lesson 08. BMI

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/python-101#74]
Hello team,

I would like to report a typo in this [page](https://www.codedex.io/python/08-bmi).

There is a mismatch between the plurality of the verb and the subject of the following sentence:

'_The parentheses is optional here, because of the order of operations._'

The string 'is' should be replace with 'are'. 

Please see attached picture for more context. 👇
![Screenshot_2023-10-29_19-45-52](https://github.com/codedex-io/python-101/assets/48260426/39c94888-950b-47d6-871b-adc0969aba8f)

**Comment by sonnynomnom** [comment]
Updated: https://github.com/codedex-io/curriculum/commit/ed1c86ee37c2fe2dd2a51b3263463e714182028d

+2!
