### ISSUE TITLE
Typo in python lesson 19. Detention

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/python-101#75]
Hello team,

I would like to report a typo in this [page](https://www.codedex.io/python/19-detention).

The string 'computer' should be replace with 'computers'. 

The first noun, modifier, verb, or pronoun must agree in number with the others in a clause.

Please see attached picture for more context. 👇
![Screenshot_2023-10-29_20-16-20](https://github.com/codedex-io/python-101/assets/48260426/9700209a-1f76-47c1-a17a-44246d8e1a93)

**Comment by sonnynomnom** [comment]
+2! Updated and closed issue:

https://github.com/codedex-io/curriculum/commit/447e9e0cf21f35ad17fe33c70f8d63b9fcfcd7ea
