### ISSUE TITLE
Trailing spaces in file 17_enter_pin.py

### ISSUE THREAD

**Issue by MilanGrujicic** [codedex-io/python-101#81]
Hello team,

I would like to report an issue in this [file](https://github.com/codedex-io/python-101/blob/main/4-loops/17_enter_pin.py).

There are some trailing space on line 4. Removing the trailing space would make the file look more professional.

See attached picture for context. 
![Screenshot_2023-10-30_11-09-07](https://github.com/codedex-io/python-101/assets/48260426/623b8e25-416b-4304-bb33-3e3566ee7fcf)

**Comment by sonnynomnom** [comment]
This is a +0 Milan, I'm sorry. Not really a bug. I was debating on -2 here here but decided to just keep it 0 instead.

I'm deleting the submission tho!
