### ISSUE TITLE
Built in function word "type" reassigned in lesson 38

### ISSUE THREAD

**Issue by intelagense** [codedex-io/python-101#82]
# Description

The attribute name "type" is used in the `Pokemon` class. However, "type" is a built-in function in Python, and reusing it as an attribute name might lead to confusion and potential issues.

## Proposed Solution:
Rename the attribute "type" to something like "pokemon_type" to avoid conflicts with the built-in `type` function.

## Code Reference:

https://github.com/codedex-io/python-101/blob/be17c21d4c4fead3c095a003a7327b1a05eada6a/7-classes-objects/38_pokedex.py#L8C5-L8C21

**Comment by sonnynomnom** [comment]
Fixed and closing!
