### ISSUE TITLE
python-101/7-classes-objects /37_bank_accounts.py

### ISSUE THREAD

**Issue by copycode69** [codedex-io/python-101#90]
**PIN as a String:** Ensured the PIN is stored as a string.
**Deposit/Withdrawal Checks:** Added validation to ensure that amounts are positive and that sufficient funds are available for withdrawals.
**Return Messages:** Updated the deposit and withdrawal methods to return informative messages.

**Comment by sonnynomnom** [comment]
Closing this! Let's keep it as simple as possible~
